### ISSUE TITLE
default `runScroll` function is not memoized

### ISSUE THREAD

**Issue by mariaines** [dotcore64/react-stay-scrolled#107]
This causes derived functions e.g. `stayScrolled` to change every render, so doing:
```js
   const { stayScrolled } = useStayScrolled(messagesContainerRef);
    useLayoutEffect(() => {
        stayScrolled()
    }, [numMessages, stayScrolled]);
```
causes `stayScrolled` to run unnecessarily. 

Proposed fix to `index.js`:
```js
export default (domRef, {
  initialScroll = null,
  inaccuracy = 0,
  runScroll
} = {}) => {
  if (!runScroll) {
    runScroll =  useCallback((offset) => { domRef.current.scrollTop = offset; }, [domRef]);
  }
   ....
};
```

Happy to submit a PR if this sounds good.

**Comment by perrin4869** [comment]
Interesting, yeah, I missed that!
Hm... that solution is not very good because hooks should never be called from inside an `if` or a loop... Need to think of a better solution.
One possible (breaking) solution is to have `runScroll` accept a DOM element as an argument too (I think this was the behavior in the past).

```javascript
const defaultRunScroll = (dom, offset) => { dom.scrollTop = offset; };

export default (domRef, {
  initialScroll = null,
  inaccuracy = 0,
  runScroll = defaultRunScroll,
} = {}) => {
  ...
  const scroll = useCallback((position) => {
    invariant(domRef.current !== null, `Trying to scroll to the bottom, but no element was found.
      Did you call this scrollBottom before the component with this hook finished mounting?`);

    const offset = Math.min(maxScrollTop(domRef.current), position);
    runScroll(domRef.current, offset);
  }, [runScroll]);

  ...
}
```

What do you think? This would be breaking for people running a custom `runScroll` like me lol

**Comment by perrin4869** [comment]
If you think that's good, if you can submit a PR with that solution and a regression test, I'll merge it in!! Thanks!

**Comment by mariaines** [comment]
> Hm... that solution is not very good because hooks should never be called from inside an `if` or a loop...

^^ Of course, whoops  🤦‍♀ 

Your solution SGTM, will send a PR soon! Sorry for the breaking change 🙁
